In [ ]:
#John David Conley
#Deep Learning assignment 3

#1. Create a class Employee and then do the following
#• Create a data member to count the number of Employees
#• Create a constructor to initialize name, family, salary, department
#• Create a function to average salary
#• Create a Fulltime Employee class and it should inherit the properties of Employee class
#• Create the instances of Fulltime Employee class and Employee class and call their member functions.

#2. Numpy
#Using NumPy create random vector of size 20 having only float in the range 1-20. 
#Then reshape the array to 4 by 5
#Then replace the max in each row by 0 (axis=1)
#(you can NOT implement it via for loop)


In [7]:
#1
counter = 0
listSal = list()
class Employee ():
    def __init__(self, name, family, salary, department): 
       self.name = name
       self.family = family
       self.salary = salary
       self.department = department
    def counting (self):
        global counter
        global listSal
        counter = counter + 1
        listSal.append(self.salary)
    def averSal (self):
        global counter
        global listSal
        sum = 0
        for n in listSal:
            sum = sum + n
        average = sum/counter
        print("The average salary is " + str(average) + ".")
        
class Fulltime (Employee):
    def __init__(self, name, family, salary, department): 
       super().__init__(name, family, salary, department)
    
emp1 = Employee("SuS", "a", 10001, "mh")
emp1.counting()
emp2 = Employee("SaS", "a", 10002, "hm")
emp2.counting()
emp3 = Employee("SoS", "a", 10003, "fm")
emp3.counting()
emp4 = Employee("SeS", "a", 10004, "kf")
emp4.counting()
emp5 = Fulltime("SiS", "a", 10005, "hd")
emp5.counting()
emp6 = Employee("SyS", "a", 10006, "gn")
emp6.counting()
emp7 = Employee("ShS", "a", 10007, "qg")
emp7.counting()
emp8 = Fulltime("SwS", "a", 10008, "ba")
emp8.counting()

emp1.averSal ()
   

The average salary is 10004.5.


In [22]:
#2
import numpy as np
vec = np.random.uniform(1,20,20)
print(vec)
print()

vec = vec.reshape(4,5)
print(vec)
print()

axMax = np.amax(vec, axis=1)
vec = np.where(np.isin(vec, axMax), 0, vec)
print(vec)

[ 7.65829371  3.20522166 12.31986461  1.1511895  19.43484226  3.45356992
 18.62640722  2.0440971   4.33827263 19.55617859  4.5903843  17.25153692
 17.73041473 14.18356546  2.16612559  3.46853328  2.95362898 19.15703031
  6.76577752  6.22578609]

[[ 7.65829371  3.20522166 12.31986461  1.1511895  19.43484226]
 [ 3.45356992 18.62640722  2.0440971   4.33827263 19.55617859]
 [ 4.5903843  17.25153692 17.73041473 14.18356546  2.16612559]
 [ 3.46853328  2.95362898 19.15703031  6.76577752  6.22578609]]

[[ 7.65829371  3.20522166 12.31986461  1.1511895   0.        ]
 [ 3.45356992 18.62640722  2.0440971   4.33827263  0.        ]
 [ 4.5903843  17.25153692  0.         14.18356546  2.16612559]
 [ 3.46853328  2.95362898  0.          6.76577752  6.22578609]]
